services:
  - type: web
    name: neural-navigator
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
